.github/workflows/maven.yml

Create a yml file for Github Actions to run automated testing on pull requests and merges to master.
See [here](https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven) for more info.

create maven yml file to run automated testing

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java

This just changes the narrative to our copy, which will allow us to modify the FBA parameters with Selenium.

feat(guiform): changed narrative id to clone

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java

Boolean values can now be pulled by the webdriver from the GUI. 
In this merge, Lines 65-70 check the checklist in the GUI and pass them into the following variables:
fluxVariabilityAnalysisValue (first boolean)
simulateAllSingleKosValue (2nd)
minimizeFluxValue (3rd)
The fourth value in the spreadsheet (the float) is also working. Users must enter a number, but there is no limit on that number yet. 
This update makes it possible for the web driver to grab the data from the GUI

GUI Work for Iteration 1

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java

add functionality to click checkboxes of first three parameters and set value of fourth
Important note: if the narrative blocks on kbase are rearranged then the code will grab the wrong narrative.

add code to do basic parameter changes on kbase

---

src/main/java/edu/iastate/ece/sd/sdmay2126/App.java
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/orchestration/Job.java
src/main/java/edu/iastate/ece/sd/sdmay2126/orchestration/JobCanceled.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/Runner.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumApplicationExecutor.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumApplicationExecutor.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumRunner.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/authentication/SeleniumAuthenticationFlow.java

#30 
I attempted but was unfruitful so far in getting the run button to work after resetting. I am unable to find it on the page with the couple of selectors that I've tried. I will keep working towards that.

Feature - Reset the FBA App

---

src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumApplicationExecutor.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumApplicationExecutor.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumIdentificationException.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumRunner.java

feature - run and reset the kbase fba app

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumApplicationExecutor.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumUtilities.java

changed warning message to red
added try catch to double click on FBASeleniumApplicationExecutor
added input for reaction to maximize.

added raction to maximize input

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java

Added gene knockouts to GUI, I believe for the selenium input programmer it works too, but needs further testing down the line.

Implement gene knockouts

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/util/RandomUtil.java
src/test/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumOutputCollectorTest.java

GUI is Good for iteration 2. The variables get passed to the driver for all basic variables. Random tests are also working in regards to sending the data to the driver.

Gui iteration2

---

src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java

note I did not change gui form so getting input from gui to params needs to be implementd.

add reaction knocut to FBASeleniumInputProgrammer

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form

Adding an XML Fix for a null pointer.

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumRunner.java
src/test/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumOutputCollectorTest.java

Adding the rest of the float and string variables to the gui form and the selenium input programmer
closes #54

Integrate basic variables

---

app.config
src/main/java/edu/iastate/ece/sd/sdmay2126/App.java
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumConfiguration.java

Created copy of FBA model
identifier is: ws.82687.obj.18
changed identifier parameter from int to String

This is an attempt to fix Issue #64

---

README.md
src/main/java/edu/iastate/ece/sd/sdmay2126/App.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/FileInputReader.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/IncorrectFBAFileConfigurationException.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/InputObjects/FBAParametersJSONObject.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/JSONFileInputReader.java
src/test/java/edu/iastate/ece/sd/sdmay2126/input/JSONFileInputReaderTest.java
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_invalid_file.json
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_valid_file.json

Allow for inputs from a configuration file that will skip the GUI.
Also updates the README to contain instructions on install / setup.
Pre-Req to #60 
Closes #66, #7

Feature - Add file reading to read in configs for FBA.

---

app.config
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java

Gene knockout fix

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java

This was originally intended to be the "sampling" functionality, but after I implemented what I thought was random samping I then learned what Dr. Cohen actually meant. Instead of throwing away the work I decided to add this feature where the user can select variables they want static and the rest be randomized. Testing of the branch is Iffy since we are getting hung up in KBase, but the runner did get the correct values which gives me some level of confidence.

Controlled Random Functionality added

---

Dockerfile
README.md
pom.xml
src/main/java/edu/iastate/ece/sd/sdmay2126/App.java
src/main/java/edu/iastate/ece/sd/sdmay2126/configuration/ConfigurationLoader.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/SeleniumRunner.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/driver/SeleniumDriverChromeRemote.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/driver/SeleniumDriverUtilities.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/driver/SeleniumDrivers.java

This PR adds the ability to run the application pointing at a Docker container for a Selenium WebDriver. This allows us to get away from requiring users to install web drivers matching their specific browser on their machines.
Continues progress on #60 
Closes #7

Feature - Dockerize Application - WebDriver

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java

Added Media Supplement Variable, at first I created a list of strings, but it turns out KBase doesn't need a list of strings :( .

Implement media supplement

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/InputObjects/FBAParametersJSONObject.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_valid_file.json

Added custom flux bounds variable to gui and automated input

Custom flux bounds

---

app.config

I created what I hope is a minimum narrative which contains an FBA card. It's basically the FBA card, genome, and media in Mikaela's narrative but without the documentation/extraneous cards.
https://narrative.kbase.us/narrative/85762
This PR updates our repo to use a copy of this minimum FBA narrative. PRs to follow as I work through fixing problems in the automation.

feat(app.config): update narrative to minimum fba

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/authentication/globus/GlobusAuthenticationFlow.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/driver/SeleniumDriverChromeRemote.java

Combining the functinonality tonight

File Reading. 

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form

I removed my button on my first pull request because others had worked on the XML and I wanted to avoid the issue of it erroring out and being unable to access from IDEs. This branch has all the XML elements that master had plus mine, so I am just cleanly adding a checkbox in.

adding my button back in. Removed it to avoid XML conflicts of the past.

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.form
src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/InputObjects/FBAParametersJSONObject.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumInputProgrammer.java
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_valid_file.json

I updated geneknockouts, customfluxbounds, and mediaSupplement to take in Lists instead of singles. Also there is still a pending bug on Kbases filtering that needs to be addressed.

Fix gui options align

---

src/main/java/edu/iastate/ece/sd/sdmay2126/runner/selenium/FBASeleniumOutputCollector.java

Just so we won't forget to change them to something reactive.

docs(fbaseleniumoutputcollector): add todos to thread.sleeps

---

src/main/java/edu/iastate/ece/sd/sdmay2126/GUIForm.java
src/main/java/edu/iastate/ece/sd/sdmay2126/application/FBAParameters.java
src/main/java/edu/iastate/ece/sd/sdmay2126/input/InputObjects/FBAParametersJSONObject.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/selenium/SeleniumKBaseHelper.java
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_valid_file_multiple.json
src/test/java/edu/iastate/ece/sd/sdmay2126/input/test_input_json_valid_file_single.json

Adds fixes for missing parameters that caused config files to crash.
Better way to enforce these params staying in sync? Would recommend adding the parameter directly to the constructor method when adding a new one so everywhere that uses the object throws an error and can be updated (including the json object).

Multiple jobs file

---

src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/application/fluxbalanceanalysis/FBASeleniumInputProgrammer.java

Please pull this and try it out before approving. Not everyone had this error so I want to make sure that the people who have not been experiencing the error, have an FBA that still works after the changes that I have made in this PR.

Rearranged the variable inputs to be in the order of the FBA form

---

src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/application/fluxbalanceanalysis/FBAResultsCardDeleter.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/application/fluxbalanceanalysis/FBASeleniumInputProgrammer.java
src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/selenium/SeleniumKBaseHelper.java

reseting no longer relies on exception.

Moved reset functionality to kbase helper

---

src/main/java/edu/iastate/ece/sd/sdmay2126/runner/gui/authentication/globus/GlobusAuthenticationFlow.java

Changed duration time from 10 secs to 30. Ten seconds started counting as soon as the application started and seemed not long enough. I also added globus button retries to avoid getting hung up

Fix globus login hang
